# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 81ade95ecef47fdc9ab9f306e4783627e326e0333a457234548135826647b6512d38583ce97588ec222a681a555b8a171ca2a721c616faa740002cb4e2071168

test:
  secret_key_base: 9fe0b13b39991ec6771bf59097a2a3147ed9d8d36e885b5535dbea3628fa06b855a1e6e7e7e522ae5f05593cbe24f41fecf53c491b552ad0802ea5718f384b8b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
